runs:
  using: "composite"
  steps:
    - name: fail
      continue-on-error: true
      shell: bash
      run: |
        : Die
        exit 1
    - name: log
      shell:  bash
      run: |
        : Log
        echo '::notice ::The weather forecast is delightful'
        exit $exit_code
